### PR TITLE
add a REQUIRE file

### PR DESCRIPTION
**Pull request by tkelman**
assuming this is untested with 0.2

### CODE REVIEW

**Comment by timholy** [comment]
In this case there's no "legacy" 0.2 install base that I'd be worried about borking with updates. Isn't that the main reason to exclude old untested versions?

**Comment by tkelman** [comment]
It's registered, so anyone who happens to be using 0.2 without knowing any better could try to add the package and they'd be allowed to. If they'd get something remotely usable then we could lower the floor.

**Comment by timholy** [comment]
But if we make it uninstallable on 0.2, how likely is that to happen?

**Comment by tkelman** [comment]
Existing tagged versions will be installable on 0.2 unless we go into metadata and add a floor to those tags. That would be the right thing to do if package authors are properly diligent about Julia version requirements, but so far things have been much more lax. I've been doing lots of drive-by PR's on this to hopefully get people to start thinking about the issue. At least 0.3 will be easier to test against going forward than 0.2 is.

**Pull request merged**
