### PR TITLE
Implement `isinteger`

### PR DESCRIPTION
**Pull request by MilesCranmer**

### CODE REVIEW

**Comment by timholy** [comment]
FYI the only reason this hasn't been released yet is because TagBot seems to not be working; I'd like to generate the tag for 0.4.4 (0372844d456a1e65bb8f2edd74890b9d8539e5ae) before releasing 0.4.5. Any ideas?

**Comment by MilesCranmer** [comment]
Very weird. I’m not sure.

**Comment by MilesCranmer** [comment]
You can generate it from the releases page manually right?

**Comment by MilesCranmer** [comment]
Here: 
Screenshot 2023-06-07 at 8 22 30 AM

(This is the same notes that TagBot generates)

**Comment by timholy** [comment]
TIL! Thanks so much, I had no idea this was possible.

**Pull request merged**
